# Generated by Django 4.2.7 on 2023-11-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="likebutton",
            name="likes",
            field=models.ManyToManyField(blank=True, to="user.user"),
        ),
    ]
