# Generated by Django 4.2.7 on 2023-11-07 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_likebutton_likes"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LikeButton",
        ),
    ]
