# Generated by Django 4.2.7 on 2023-11-07 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_delete_likebutton"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="cpassword",
            new_name="email",
        ),
    ]
