# Generated by Django 4.2.7 on 2023-11-07 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_rename_cpassword_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="password",
        ),
    ]
